// Generated by gencpp from file cyber_common_msgs/StatusPb.msg
// DO NOT EDIT!


#ifndef CYBER_COMMON_MSGS_MESSAGE_STATUSPB_H
#define CYBER_COMMON_MSGS_MESSAGE_STATUSPB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cyber_common_msgs/ErrorCode.h>

namespace cyber_common_msgs
{
template <class ContainerAllocator>
struct StatusPb_
{
  typedef StatusPb_<ContainerAllocator> Type;

  StatusPb_()
    : error_code()
    , msg()  {
    }
  StatusPb_(const ContainerAllocator& _alloc)
    : error_code(_alloc)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::cyber_common_msgs::ErrorCode_<ContainerAllocator>  _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::cyber_common_msgs::StatusPb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyber_common_msgs::StatusPb_<ContainerAllocator> const> ConstPtr;

}; // struct StatusPb_

typedef ::cyber_common_msgs::StatusPb_<std::allocator<void> > StatusPb;

typedef boost::shared_ptr< ::cyber_common_msgs::StatusPb > StatusPbPtr;
typedef boost::shared_ptr< ::cyber_common_msgs::StatusPb const> StatusPbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyber_common_msgs::StatusPb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cyber_common_msgs::StatusPb_<ContainerAllocator1> & lhs, const ::cyber_common_msgs::StatusPb_<ContainerAllocator2> & rhs)
{
  return lhs.error_code == rhs.error_code &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cyber_common_msgs::StatusPb_<ContainerAllocator1> & lhs, const ::cyber_common_msgs::StatusPb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cyber_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyber_common_msgs::StatusPb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_common_msgs::StatusPb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_common_msgs::StatusPb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e698cfb387df649f1e7c2a110faf511f";
  }

  static const char* value(const ::cyber_common_msgs::StatusPb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe698cfb387df649fULL;
  static const uint64_t static_value2 = 0x1e7c2a110faf511fULL;
};

template<class ContainerAllocator>
struct DataType< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyber_common_msgs/StatusPb";
  }

  static const char* value(const ::cyber_common_msgs::StatusPb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ErrorCode error_code\n"
"string msg\n"
"================================================================================\n"
"MSG: cyber_common_msgs/ErrorCode\n"
"# No error, returns on success.\n"
"uint16  OK = 0\n"
"\n"
"# Control module error codes start from here.\n"
"uint16  CONTROL_ERROR = 1000\n"
"uint16  CONTROL_INIT_ERROR = 1001\n"
"uint16  CONTROL_COMPUTE_ERROR = 1002\n"
"uint16  CONTROL_ESTOP_ERROR = 1003\n"
"uint16  PERFECT_CONTROL_ERROR = 1004\n"
"\n"
"# Canbus module error codes start from here.\n"
"uint16  CANBUS_ERROR = 2000\n"
"uint16  CAN_CLIENT_ERROR_BASE = 2100\n"
"uint16  CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED = 2101\n"
"uint16  CAN_CLIENT_ERROR_FRAME_NUM = 2102\n"
"uint16  CAN_CLIENT_ERROR_SEND_FAILED = 2103\n"
"uint16  CAN_CLIENT_ERROR_RECV_FAILED = 2104\n"
"\n"
"# Localization module error codes start from here.\n"
"uint16  LOCALIZATION_ERROR = 3000\n"
"uint16  LOCALIZATION_ERROR_MSG = 3100\n"
"uint16  LOCALIZATION_ERROR_LIDAR = 3200\n"
"uint16  LOCALIZATION_ERROR_INTEG = 3300\n"
"uint16  LOCALIZATION_ERROR_GNSS = 3400\n"
"\n"
"# Perception module error codes start from here.\n"
"uint16  PERCEPTION_ERROR = 4000\n"
"uint16  PERCEPTION_ERROR_TF = 4001\n"
"uint16  PERCEPTION_ERROR_PROCESS = 4002\n"
"uint16  PERCEPTION_FATAL = 4003\n"
"uint16  PERCEPTION_ERROR_NONE = 4004\n"
"uint16  PERCEPTION_ERROR_UNKNOWN = 4005\n"
"\n"
"# Prediction module error codes start from here.\n"
"uint16  PREDICTION_ERROR = 5000\n"
"\n"
"# Planning module error codes start from here\n"
"uint16  PLANNING_ERROR = 6000\n"
"uint16  PLANNING_ERROR_NOT_READY = 6001\n"
"\n"
"# HDMap module error codes start from here\n"
"uint16  HDMAP_DATA_ERROR = 7000\n"
"\n"
"# Routing module error codes\n"
"uint16  ROUTING_ERROR = 8000\n"
"uint16  ROUTING_ERROR_REQUEST = 8001\n"
"uint16  ROUTING_ERROR_RESPONSE = 8002\n"
"uint16  ROUTING_ERROR_NOT_READY = 8003\n"
"\n"
"# Indicates an input has been exhausted.\n"
"uint16  END_OF_INPUT = 9000\n"
"\n"
"# HTTP request error codes.\n"
"uint16  HTTP_LOGIC_ERROR = 10000\n"
"uint16  HTTP_RUNTIME_ERROR = 10001\n"
"\n"
"# Relative Map error codes.\n"
"uint16  RELATIVE_MAP_ERROR = 11000  # general relative map error code\n"
"uint16  RELATIVE_MAP_NOT_READY = 11001\n"
"\n"
"# Driver error codes.\n"
"uint16  DRIVER_ERROR_GNSS = 12000\n"
"uint16  DRIVER_ERROR_VELODYNE = 13000\n"
"\n"
"# Storytelling error codes.\n"
"uint16  STORYTELLING_ERROR = 14000\n"
"\n"
"uint16 code\n"
;
  }

  static const char* value(const ::cyber_common_msgs::StatusPb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusPb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyber_common_msgs::StatusPb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyber_common_msgs::StatusPb_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    s << std::endl;
    Printer< ::cyber_common_msgs::ErrorCode_<ContainerAllocator> >::stream(s, indent + "  ", v.error_code);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBER_COMMON_MSGS_MESSAGE_STATUSPB_H
