// Generated by gencpp from file cyber_perception_msgs/ObstacleSubType.msg
// DO NOT EDIT!


#ifndef CYBER_PERCEPTION_MSGS_MESSAGE_OBSTACLESUBTYPE_H
#define CYBER_PERCEPTION_MSGS_MESSAGE_OBSTACLESUBTYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyber_perception_msgs
{
template <class ContainerAllocator>
struct ObstacleSubType_
{
  typedef ObstacleSubType_<ContainerAllocator> Type;

  ObstacleSubType_()
    : type(0)  {
    }
  ObstacleSubType_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(UNKNOWN_MOVABLE)
  #undef UNKNOWN_MOVABLE
#endif
#if defined(_WIN32) && defined(UNKNOWN_UNMOVABLE)
  #undef UNKNOWN_UNMOVABLE
#endif
#if defined(_WIN32) && defined(CAR)
  #undef CAR
#endif
#if defined(_WIN32) && defined(VAN)
  #undef VAN
#endif
#if defined(_WIN32) && defined(TRUCK)
  #undef TRUCK
#endif
#if defined(_WIN32) && defined(BUS)
  #undef BUS
#endif
#if defined(_WIN32) && defined(CYCLIST)
  #undef CYCLIST
#endif
#if defined(_WIN32) && defined(MOTORCYCLIST)
  #undef MOTORCYCLIST
#endif
#if defined(_WIN32) && defined(TRICYCLIST)
  #undef TRICYCLIST
#endif
#if defined(_WIN32) && defined(PEDESTRIAN)
  #undef PEDESTRIAN
#endif
#if defined(_WIN32) && defined(TRAFFICCONE)
  #undef TRAFFICCONE
#endif

  enum {
    UNKNOWN = 0u,
    UNKNOWN_MOVABLE = 1u,
    UNKNOWN_UNMOVABLE = 2u,
    CAR = 3u,
    VAN = 4u,
    TRUCK = 5u,
    BUS = 6u,
    CYCLIST = 7u,
    MOTORCYCLIST = 8u,
    TRICYCLIST = 9u,
    PEDESTRIAN = 10u,
    TRAFFICCONE = 11u,
  };


  typedef boost::shared_ptr< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleSubType_

typedef ::cyber_perception_msgs::ObstacleSubType_<std::allocator<void> > ObstacleSubType;

typedef boost::shared_ptr< ::cyber_perception_msgs::ObstacleSubType > ObstacleSubTypePtr;
typedef boost::shared_ptr< ::cyber_perception_msgs::ObstacleSubType const> ObstacleSubTypeConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator1> & lhs, const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator1> & lhs, const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cyber_perception_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feaa08b02302a47fbeed5eaf45655cb6";
  }

  static const char* value(const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfeaa08b02302a47fULL;
  static const uint64_t static_value2 = 0xbeed5eaf45655cb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyber_perception_msgs/ObstacleSubType";
  }

  static const char* value(const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8  UNKNOWN = 0\n"
"uint8  UNKNOWN_MOVABLE = 1\n"
"uint8  UNKNOWN_UNMOVABLE = 2\n"
"uint8  CAR = 3\n"
"uint8  VAN = 4\n"
"uint8  TRUCK = 5\n"
"uint8  BUS = 6\n"
"uint8  CYCLIST = 7\n"
"uint8  MOTORCYCLIST = 8\n"
"uint8  TRICYCLIST = 9\n"
"uint8  PEDESTRIAN = 10\n"
"uint8  TRAFFICCONE = 11\n"
"\n"
"uint8 type\n"
;
  }

  static const char* value(const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleSubType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyber_perception_msgs::ObstacleSubType_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBER_PERCEPTION_MSGS_MESSAGE_OBSTACLESUBTYPE_H
